Name:           ros-melodic-nmea-to-geopose
Version:        0.0.1
Release:        1%{?dist}
Summary:        ROS nmea_to_geopose package

Group:          Development/Libraries
License:        Apachi 2
Source0:        %{name}-%{version}.tar.gz

Requires:       eigen3-devel
Requires:       glog-devel
Requires:       ros-melodic-geodesy
Requires:       ros-melodic-geographic-msgs
Requires:       ros-melodic-nmea-msgs
Requires:       ros-melodic-quaternion-operation
Requires:       ros-melodic-roscpp
BuildRequires:  eigen3-devel
BuildRequires:  glog-devel
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-geodesy
BuildRequires:  ros-melodic-geographic-msgs
BuildRequires:  ros-melodic-nmea-msgs
BuildRequires:  ros-melodic-quaternion-operation
BuildRequires:  ros-melodic-roscpp

%description
The nmea_to_geopose package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Sun Jun 30 2019 Masaya Kataoka <ms.kataoka@gmail.com> - 0.0.1-1
- Autogenerated by Bloom

